"""Minimal Phase B / early Phase C L3 deliberation skeleton."""

from ..anchor import ActionDomain, AgentState, CandidateSchema, apply_structural_anchors, build_action_domain
from .contracts import Candidate, CandidateAssessment, DeliberationAuditRecord, DeliberationInput, ReleaseDecision, ReleaseToken
from .memory import (
    ADAPTER_MODE_HEURISTIC,
    ADAPTER_MODE_INERT,
    ClientBackedWorkingMemoryAdapter,
    HabitBiasSummary,
    HabitSkillSummary,
    HeuristicWorkingMemoryAdapter,
    HeuristicWorkingMemoryModelClient,
    LearningOutcomeRecord,
    MemoryWriteStub,
    MODEL_CLIENT_MODE_HEURISTIC,
    MODEL_CLIENT_MODE_INERT,
    MODEL_CLIENT_MODE_LIVE,
    NullWorkingMemoryAdapter,
    NullWorkingMemoryModelClient,
    OpenAICompatibleWorkingMemoryModelClient,
    OpenAICompatibleWorkingMemoryModelClientConfig,
    WorkingMemoryAdapter,
    WorkingMemoryAdapterRequest,
    WorkingMemoryAdapterResponse,
    WorkingMemoryModelClient,
    WorkingMemoryModelClientConfig,
    WorkingMemoryModelClientRequest,
    WorkingMemoryModelClientResponse,
    build_builtin_working_memory_adapter,
    build_builtin_working_memory_model_client,
    build_learning_outcome_record,
    build_memory_stub,
    build_situation_key_from_values,
    derive_habit_skills,
    evaluate_response_outcome,
    summarize_habit_bias,
)
from .peer_circuit import decide_release
from .reasoning import (
    WorkingMemoryContext,
    assess_candidates,
    build_candidates,
    build_llm_working_memory_context,
    build_situation_key,
    build_working_memory_context,
    build_working_memory_context_from_store,
)
from .runtime import build_deliberation_input, build_deliberation_input_from_store, run_deliberation

__all__ = [
    "ActionDomain",
    "AgentState",
    "Candidate",
    "CandidateAssessment",
    "CandidateSchema",
    "DeliberationAuditRecord",
    "DeliberationInput",
    "HabitBiasSummary",
    "HabitSkillSummary",
    "LearningOutcomeRecord",
    "MemoryWriteStub",
    "ReleaseDecision",
    "ReleaseToken",
    "WorkingMemoryContext",
    "ADAPTER_MODE_INERT",
    "ADAPTER_MODE_HEURISTIC",
    "WorkingMemoryAdapter",
    "WorkingMemoryAdapterRequest",
    "WorkingMemoryAdapterResponse",
    "NullWorkingMemoryAdapter",
    "HeuristicWorkingMemoryAdapter",
    "ClientBackedWorkingMemoryAdapter",
    "build_builtin_working_memory_adapter",
    "WorkingMemoryModelClient",
    "WorkingMemoryModelClientConfig",
    "WorkingMemoryModelClientRequest",
    "WorkingMemoryModelClientResponse",
    "NullWorkingMemoryModelClient",
    "HeuristicWorkingMemoryModelClient",
    "MODEL_CLIENT_MODE_INERT",
    "MODEL_CLIENT_MODE_HEURISTIC",
    "MODEL_CLIENT_MODE_LIVE",
    "OpenAICompatibleWorkingMemoryModelClient",
    "OpenAICompatibleWorkingMemoryModelClientConfig",
    "build_builtin_working_memory_model_client",
    "apply_structural_anchors",
    "build_action_domain",
    "assess_candidates",
    "build_candidates",
    "build_deliberation_input",
    "build_deliberation_input_from_store",
    "build_learning_outcome_record",
    "build_llm_working_memory_context",
    "build_memory_stub",
    "build_situation_key",
    "build_situation_key_from_values",
    "build_working_memory_context",
    "build_working_memory_context_from_store",
    "decide_release",
    "derive_habit_skills",
    "evaluate_response_outcome",
    "run_deliberation",
    "summarize_habit_bias",
]
